modal
FIPost/ui pull request #18
Opened 2021-04-22 13:00 UTC by robindewitte

kan het niet implementeren want mijn addroom page is nog steeds behekest met demonen

2021-04-22 14:10 UTC, ShadyDL commented
Nog niet af...

2021-04-29 08:45 UTC, ShadyDL commented
@robindewitte je moet je conflicts nog even resolven

2021-04-29 08:52 UTC, ShadyDL commented
@robindewitte kun je nog even toevoegen dat hij alle inputfields leegmaakt als je kiest voor `blijven`? De rest is goed.

2021-04-29 08:53 UTC, ShadyDL requested changes
Velden leeg maken als de gebruiker wil blijven voor het invoeren van een nieuwe locatie.

2021-04-29 09:30 UTC, robindewitte commented
Ik weet niet hoe het gebeurd is maar ik krijg het niet meer getest

2021-04-29 12:05 UTC, ShadyDL commented
@robindewitte Het is niet de bedoeling dat je de DOM aanspreekt in VueJS op deze gebruik maakt van een virtuele dom. Dus geen `document.getElementsByTag` gebruiken. Gewoon de properties van de components leegmaken.

2021-04-29 12:06 UTC, ShadyDL requested changes
@robindewitte Het is niet de bedoeling dat je de DOM aanspreekt in VueJS op deze gebruik maakt van een virtuele dom. Dus geen `document.getElementsByTag` gebruiken. Gewoon de properties van de components leegmaken.

2021-04-29 12:08 UTC, robindewitte commented
@ShadyDL ik ga eens kijken hoe ik dat dan voor elkaar krijg en of dat het probleem oplost

2021-04-30 08:44 UTC, ShadyDL approved these changes

2021-04-30 08:45 UTC, merged